### ISSUE TITLE
1.2.0 - tag

### ISSUE THREAD

**Issue by ttsda** [capaj/require-globify#10]
Hi,

I see you bumped to version 1.2.0 in the 63734a24f1350745328df9e56c31ad8525e39163 commit, but you didn't add a 1.2.0 tag, is this on purpose?

Regards

**Comment by call-a3** [comment]
Yes, the 1.2.0 version is not stable yet (some tests are not passing), so I'm holding off on a release (and matching tag) until that is resolved.

**Comment by ttsda** [comment]
I see, thanks :)
