### ISSUE TITLE
strip-ext doesn't work when called after path-reduce

### ISSUE THREAD

**Issue by mparpaillon** [capaj/require-globify#12]
This works (extensions are stripped)

```
var stuff = require('../stuff/*.js', {
    mode: 'hash',
    resolve: [ 'strip-ext', 'path-reduce' ]
});
```

This doesn't

```
var stuff = require('../stuff/*.js', {
    mode: 'hash',
    resolve: [ 'path-reduce', 'strip-ext' ]
});
```

**Comment by call-a3** [comment]
Could you elaborate on the output you would expect vs the output you are getting?

**Comment by mparpaillon** [comment]
I expect the filename without the extension... That's what strip-ext is supposed to do, right ?

**Comment by call-a3** [comment]
Yes, that is right. 

However, to more accurately debug this I'd like a literal example of input, actual output and expected output. That way, I can also turn it into a test case and ensure no regressions occur at a later point.
Sorry if I seem overly adamant about this, but it is with the best intentions for both our sakes.

**Comment by call-a3** [comment]
Investigating this because it is related to bug #13
