### ISSUE TITLE
hash does not work when only one file in the required directory

### ISSUE THREAD

**Issue by mparpaillon** [capaj/require-globify#13]
Apparently when you require a directory which only has a single file, then the key appears with the full relative path and no extension, whatever your resolve options are.

Here is the test case (Bug only shows up when only one file in the target directory):

```
// Input
var templates = require('./templates/*.hbs', { mode: 'hash' });

// Output
var templates =  {
    './templates/zoning': require('./templates/zoning.hbs')
};

// Output expected
var templates =  {
    'zoning.hbs': require('./templates/zoning.hbs')
};
```

I know ! You want tests, screenshots of it, photo of me getting the bug while evil laughing.
But I already lost too much time on this bug so do whatever you want with that information.

**Comment by call-a3** [comment]
I think you're exaggerating my expectations of a bug report, but I understand if you feel annoyed by my response on your previous bug report. I think I have everything I need from this report, so I'll look in to it as fast as I can ;)
