### ISSUE TITLE
Is there any way to use this in a testing environment?

### ISSUE THREAD

**Issue by tombh** [capaj/require-globify#15]
I've been using this module, but when it comes to testing I can't get the hash of required modules because my project isn't being transformed through browserify.

**Comment by call-a3** [comment]
What testing environment do you use? Some tools (e.g. karma) have plugins that allow you to use the same tools you use for compilation.

**Comment by tombh** [comment]
Ah yes, good point. I'm using purely server-side tests using jasmine-node. I think I've figured out a way - by detecting the environment and using the `require-dir` module for jasmine-node.
