### ISSUE TITLE
mode:list would be a good feature

### ISSUE THREAD

**Issue by epoberezkin** [capaj/require-globify#17]
Because maps are not ordered and it would be good to retain the order of files returned by glob.
At the moment I either have to convert the hash to array (with no guarantee of having the same order) or to provide a custom function.

Instead of hash it would return the array of objects with properties, for example, "name" and "module".

**Comment by call-a3** [comment]
Ok, I'll add this in the next release.

**Comment by epoberezkin** [comment]
great, thanks

**Comment by call-a3** [comment]
Should be there, can you test it and let me know if it works for you?
How important is the order of the matches? (because right now matches are sorted to ensure consistency)

**Comment by epoberezkin** [comment]
Works beautifully, I replaced :) Thank you!
https://github.com/epoberezkin/ajv/commit/73b21e0383cc4efd20567b28e27992685e5b2748
