### ISSUE TITLE
Grunt

### ISSUE THREAD

**Issue by luglio7** [capaj/require-globify#2]
Any chance we can use this with the browserify grunt package ?

**Comment by call-a3** [comment]
I'm not familiar with grunt or it's internal workings... Have you tried to use it out-of-the-box? Could you tell me what errors or other messages you get if/when this doesn't work?

**Comment by call-a3** [comment]
Closing because of lack of response. If any other people have issues with this, please ask to reopen!

**Comment by grevory** [comment]
This  works in Grunt. Thank you.
