### ISSUE TITLE
Doesn't look within node_modules

### ISSUE THREAD

**Issue by saiichihashimoto** [capaj/require-globify#22]
Doing something like:

```
require('packagename/*/something', { mode: 'hash' });
```

does not work. Instead, I have to do something like:

```
require('../../node_modules/packagename/*/something', { mode: 'hash' });
```

**Comment by call-a3** [comment]
This is correct. Right now require-globify assumes "real" relative paths, so npm packages are not recognized nor supported. I'll think of a way we can support these in the next version.

**Comment by mividtim** [comment]
I'd love to see this work!

**Comment by btknorr** [comment]
+1

**Comment by call-a3** [comment]
Allright, by popular request (:p) I'll look into this this weekend. Shouldn't be too hard to implement...

**Comment by saiichihashimoto** [comment]
@call-a3, I'm imagining life happened so this never got worked on. :-)

But actually, is there any progress on this?

**Comment by mividtim** [comment]
Any updates here?  I'll fork to work on this, if you have any ideas on where to start.
