### ISSUE TITLE
hash not working with relative paths outside of folder.

### ISSUE THREAD

**Issue by zolitch** [capaj/require-globify#5]
Hi.

There appears to be an issue with using the "hash" and "hashWithPaths" approach on thier own with relative paths outside of the current folder.

"hashWithExtensions" and "hashWithExtensionsAndPaths" both work fien but:

"hash" and "hashWithPaths" both fail with Browserify error:

 ``ERROR [framework.browserify]: Error: Cannot find module '../../modules/ModuleName' in /current folder `` In other words, "../../" seems to be ignored and it looks in the current folder for "../../foo" as the module name.

**Comment by call-a3** [comment]
I'll look into this. Please hang on...

**Comment by call-a3** [comment]
I'm working on this. If you can, please check out the develop branch to see if the new version will fix your problem?

**Comment by call-a3** [comment]
Should be fixed in 1.2.0.
I'm deploying the new version when TravisCI comes back up (it's momentarily down for maintenance) and it gives the all-green.

**Comment by zolitch** [comment]
Thanks for fixing!
