### ISSUE TITLE
Require without extension only works for JS files

### ISSUE THREAD

**Issue by mparpaillon** [capaj/require-globify#6]
In my case, I'm requiring Handlebars templates with '.hbs' extension. So it's not working when I try to require them.

So if I have a zoning.hbs file in my template/ directory and I do this
```js
var myTemplates = require('./templates/*.hbs', { hash: true });
```

I get this
```
Error: Cannot find module './templates/zoning' from ...
```

PR incoming

**Comment by call-a3** [comment]
I'll investigate this. Please follow the pull request for the resolution.
